# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A_mdTtZuLFYd5MgD73CaGReuqsNlKEtA
"""

def helper(start,end,str):
  if(start>=end):
    return
  temp = str[start]
  str[start]=str[end]
  str[end]=temp

str = ['h','e','l','l','o']
helper(0,len(str)-1,str)
print(str)